### ISSUE TITLE
move to python3 to use on matrix

### ISSUE THREAD

**Issue by keiem** [raptor2101/PodCatcher#14]
Hello,

do you have plans to move to python3 so PodCatcher can be used in Kodi Matrix?

**Comment by okkebal** [comment]
At the moment there is no way to use podcasts on Kodi Matrix since the Apple iTunes Podcast plugin is also not available for Matrix. You could try to add rss sources manually, but Kodi crashes for me if i try to use a podcast that way. 

On the kodi.tv website at the bottom it says you can use Kodi to listen to Podcasts. They should remove that message since there is no way to listen to podcasts atm

**Comment by raptor2101** [comment]
> On the kodi.tv website at the bottom it says you can use Kodi to listen to Podcasts. They should remove that message since there is no way to listen to podcasts atm

I'am not connected nore responsible for the kodi.tv website. So this is the wrong place for this discussion here.

There are no plans to submit anything further for kodi. This repo for archiv reasons.

**Comment by stobb3s** [comment]
For people who are looking for Podcast support in Kodi 19 Matrix, I recommend [https://github.com/Heckie75/kodi-addon-podcast](https://github.com/Heckie75/kodi-addon-podcast)

It works well for me.

Edit: Fixed URL

**Comment by keiem** [comment]
Thanks for the link,I will try it.
